// <auto-generated />
namespace NosSeusPes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class FinalVendas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FinalVendas));
        
        string IMigrationMetadata.Id
        {
            get { return "201909250440518_FinalVendas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
